### ISSUE TITLE
Cahnnels Quick Jump

### ISSUE THREAD

**Issue by shemerey** [shemerey/im#4]
## Channels Quick Jump

All channels should be listed in `store.channels` as a list of objects.  this list will be populated while doing initial team initialisation. 
- any channel can be only one of 2 types `@` for direct connection to the people & `#` as group chat.
- direct channel
  - should have status in a list (`on`, `off`, `away`)
  - should have (full name in addition to the username)
- group chat 
  - should have name
  - can have number of people (??)
  - can have topic (??)
### Behaviour

When you press the `hotkey` it will open a modal window with the focused input and list of `unread` channels, if now unread channels this list hast have the last one channel.
## ToDo
- [ ] define the channel object, and document it in an initial store, it has to be consistent for all possible channels and can be extended in future. This data has to have to type of fields `required` and the rest. 
- [ ] add instruction to the input (take a look at https://github.com/Osmose/advanced-open-file repo) 
- [ ] change the store to keep last visited channel
- [ ] change the store (probably add a new object to it ) in order to keep list of needed messages
- [ ] implement `join` action for `not a member` channels
- [ ] join only when you `not a member`  
#### Screenshots && UI

---

<img width="1440" alt="screen shot 2016-09-01 at 15 36 00" src="https://cloud.githubusercontent.com/assets/31591/18171384/72cddcf2-706a-11e6-91ac-1960670edf85.png">
<img width="1440" alt="screen shot 2016-09-01 at 15 35 51" src="https://cloud.githubusercontent.com/assets/31591/18171383/72c91ae6-706a-11e6-8d99-d61544883d37.png">
<img width="1440" alt="screen shot 2016-09-01 at 15 35 37" src="https://cloud.githubusercontent.com/assets/31591/18171382/72b6ae10-706a-11e6-92ce-fae0cfc55eec.png">
